# Default configuration for when a settlement gets created
settlement:
  max-claims: 15
  max-members: 10
  max-roles: 5
  max-name-length: 12
  min-name-length: 4
  max-description-length: 36
  min-description-length: 8
  max-tag-length: 4
  min-tag-length: 2

# Allow teleportation like going to claims, spawn etc
# Note: a restart is required
teleportation: true

# When the placeholder is invalid, replace it with this string.
placeholder-string: "-"

# The default flags for a settlements
# Refer to wiki for all available land flags

flags:
  - ANIMAL_SPAWNING
  - MONSTER_SPAWNING

# The default roles that get created when you make a settlement with appropriate permissions.
# Refer to wiki for all available permissions

#{name}:
#  - PERMISSION_1
#  - PERMISSION_2

roles:
  citizen:
    - SPAWN_TELEPORT
    - LAND_BREAK
    - LAND_PLACE
  veteran:
    - SPAWN_TELEPORT
    - MEMBER_INVITE
    - LAND_BREAK
    - LAND_PLACE
    - LAND_INTERACT
  royal:
    - SPAWN_TELEPORT
    - MEMBER_INVITE
    - MEMBER_KICK
    - MEMBER_KICK_EXEMPT
    - LAND_BREAK
    - LAND_PLACE
    - LAND_INTERACT

# Disable settlements in certain worlds (claiming, creation etc)
disabled-worlds:
  - world_nether
  - world_the_end