name: Settlements
main: com.huskydreaming.settlements.SettlementPlugin
version: 0.6.2
api-version: 1.20
author: HuskyDreaming
softdepend: [WorldGuard, PlaceholderAPI, Towny]
loadbefore: [EssentialsX, Essentials]

commands:
  settlements:
    description: The Settlements Command.
    aliases: [s, settle, settlement]